spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_ID}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000

  datasource:
    master:
      jdbc-url: jdbc:mariadb://${MASTER_DB}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${DB_ID}
      password: ${DB_PASSWORD}
    slave:
      jdbc-url: jdbc:mariadb://${SLAVE_DB}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${DB_ID}
      password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace